### ISSUE TITLE
Questions regaarding Ether1

### ISSUE THREAD

**Issue by DonaldTsang** [Ether1Project/Ether1#5]
Hi there, some questions:
1. Is this just IPFS that runs on top of the Ethereum blockchain?
2. The naming scheme cause confusion between ETH/ETC and Ether1?
3. How does this compare to SWARM, IPFS/Filecoin, Sia, Storj, Maidsafe?

**Comment by E1Code** [comment]
Ether-1 is an eth clone chain modified to run an incentivised network of nodes (Service Nodes, Masternodes & Gateway Nodes) that run a private IPFS network allowing for end-to-end decentralized application development and deployment. Please join our discord (https://discord.gg/RA4AZx9) if you want to know more about the economic theory behind the node network and how the reward system allows the network to scale naturally based on network resource utilization. We have a very active community!

**Comment by E1Code** [comment]
I am closing this issue. Please contact us via email or discord if you'd like to know more!
